### ISSUE TITLE
Code for generating the wasm files

### ISSUE THREAD

**Issue by fabiospampinato** [evanwashere/wasm#1]
Hello there, I'd like to convert the Rust entrypoint file for zstd to wasm on my own but without support for compressing, as I only need to decompress zstd files in the browser and I'd rather keep the bundles as small as possible, could you share the code you used to generate the wasm file? Thanks.

**Comment by evanwashere** [comment]
i saw that you already solved your issue but here is my take on it if you want it

this completely avoids emscripten and its complex bindings, for simd just change -simd128 to +simd128 

prerequisites:
- zig
- cargo
- wasm-opt from npm or binaryen

bindings:
```js
const fs = require('fs');

const wasm = new WebAssembly.Instance(new WebAssembly.Module(fs.readFileSync('./zstd.o.wasm'))).exports;

function decompress(buffer, size) {
  const ptr = wasm.malloc(buffer.length);
  new Uint8Array(wasm.memory.buffer).set(buffer, ptr);
  const optr = wasm.malloc(size ??= Number(wasm.ZSTD_findDecompressedSize(ptr, buffer.length)));

  size = wasm.ZSTD_decompress(optr, size, ptr, buffer.length);
  const slice = new Uint8Array(wasm.memory.buffer, optr, size).slice();

  return (wasm.free(ptr), wasm.free(optr), slice);
}
```

build script:
```sh
npm i wasm-opt # kinda outdated, preferably use wasm-opt from https://github.com/WebAssembly/binaryen/releases
cargo install --git https://github.com/willemneal/wasm-snip --branch feat/keep_export # cargo not needed if you copy around wasm-snip binary

git clone https://github.com/facebook/zstd

cd zstd
zig build-lib \
-lc \
--strip \
-dynamic \
--name zstd \
-O ReleaseFast \
-mcpu mvp-simd128 \
--single-threaded \
-target wasm32-wasi \
\
lib/decompress/*.c \
lib/common/xxhash.c \
lib/common/zstd_common.c \
lib/common/error_private.c \
lib/common/entropy_common.c \
lib/common/fse_decompress.c && \
\
wasm-snip zstd.wasm -k free -k malloc -k ZSTD_decompress -k ZSTD_findDecompressedSize -o zstd.wasm && \
~/Downloads/binaryen-version_*/bin/wasm-opt -O4 --dce --detect-features -o zstd.wasm zstd.wasm
```

**Comment by fabiospampinato** [comment]
Awesome, thank you, I should try and see how big and fast the generated wasm would be that way.

**Comment by evanwashere** [comment]
you can also replace wasm-snip with wasm-ld (from llvm)

`zig build-lib ... --verbose-link`
replace `--export-all` with `--export free --export malloc --export ZSTD_decompress --export ZSTD_findDecompressedSize` and rerun

that will produce the smallest possible wasm with zig runtime

**Comment by fabiospampinato** [comment]
@evanwashere Kind of an off-topic question, but do you happen to know how to generate an asm.js build  rather than a wasm one? 

I've been playing with decompressing zstd archives in the browser and for my use case if the decompressor were even 100x slower I might not even notice, so I might want to trade some performance for smaller bundle sizes, and for my use case I pretty much need to base64-encode the wasm file while I wouldn't have to do that with an asm.js build, which should be significant for bundle sizes.

**Comment by evanwashere** [comment]
wasm2js from https://github.com/WebAssembly/binaryen#tools
in my tests asm.js actually ends up being bigger than base64 wasm when bundled with esbuild, but you are free to tinker more with it

if your goal is size then you can replace optimization options with `-Os` and `-O ReleaseSmall`

**Comment by fabiospampinato** [comment]
I just tried that, it's not really compiling a WASM file to JS or ASM.js though, it's just base64-encoding the WASM file and adding some wrapper code around that, that's kind of heavier by definition.

**Comment by evanwashere** [comment]
base64 is data section of wasm
![image](https://user-images.githubusercontent.com/70155278/120927178-ee9f6f00-c6ad-11eb-87ab-e649201f2f3c.png)

everything else is asm.js

**Comment by fabiospampinato** [comment]
Wait I think I installed the wrong thing 🤦‍♂️ https://www.npmjs.com/package/wasm2js

**Comment by evanwashere** [comment]
you can download binaryen tools from https://github.com/WebAssembly/binaryen/releases/latest

**Comment by fabiospampinato** [comment]
Thanks for the link. As you say it's not worth it, I got a JS file that's 2x larger.

**Comment by fabiospampinato** [comment]
I've tried generating the WASM with your snippet but Zig doesn't seem to want give me an easy time on this:

```
error(compilation): clang failed with stderr: In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/libunwind.cpp:12:
In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/include/libunwind.h:16:
/usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/include/__libunwind_config.h:139:4: error: "Unsupported architecture."
In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/libunwind.cpp:12:
/usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/include/libunwind.h:65:17: error: use of undeclared identifier '_LIBUNWIND_CONTEXT_SIZE'
/usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/include/libunwind.h:70:17: error: use of undeclared identifier '_LIBUNWIND_CURSOR_SIZE'
In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/libunwind.cpp:14:
In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/libunwind_ext.h:15:
/usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/config.h:16:10: fatal error: 'assert.h' file not found

error(compilation): clang failed with stderr: In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/Unwind-EHABI.cpp:12:
In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/Unwind-EHABI.h:13:
/usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/include/__libunwind_config.h:139:4: error: "Unsupported architecture."

error(compilation): clang failed with stderr: In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/Unwind-seh.cpp:13:
/usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/config.h:16:10: fatal error: 'assert.h' file not found

error(compilation): clang failed with stderr: In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/UnwindLevel1.c:21:
/usr/local/Cellar/zig/0.7.1/lib/zig/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found

error(compilation): clang failed with stderr: In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/UnwindLevel1-gcc-ext.c:12:
/usr/local/Cellar/zig/0.7.1/lib/zig/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found

error(compilation): clang failed with stderr: In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/Unwind-sjlj.c:12:
In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/include/unwind.h:16:
/usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/include/__libunwind_config.h:139:4: error: "Unsupported architecture."
In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/Unwind-sjlj.c:14:
/usr/local/Cellar/zig/0.7.1/lib/zig/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found

error(compilation): clang failed with stderr: In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/UnwindRegistersRestore.S:9:
/usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/assembly.h:137:2: error: Unsupported target

error(compilation): clang failed with stderr: In file included from /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/UnwindRegistersSave.S:9:
/usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/assembly.h:137:2: error: Unsupported target

error(compilation): /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/libunwind.cpp:1:1: unable to build C object: clang exited with code 1

error(compilation): /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/Unwind-EHABI.cpp:1:1: unable to build C object: clang exited with code 1

error(compilation): /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/Unwind-seh.cpp:1:1: unable to build C object: clang exited with code 1

error(compilation): /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/UnwindLevel1.c:1:1: unable to build C object: clang exited with code 1

error(compilation): /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/UnwindLevel1-gcc-ext.c:1:1: unable to build C object: clang exited with code 1

error(compilation): /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/Unwind-sjlj.c:1:1: unable to build C object: clang exited with code 1

error(compilation): /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/UnwindRegistersRestore.S:1:1: unable to build C object: clang exited with code 1

error(compilation): /usr/local/Cellar/zig/0.7.1/lib/zig/libunwind/src/UnwindRegistersSave.S:1:1: unable to build C object: clang exited with code 1

error: unable to build libunwind: BuildingLibCObjectFailed
```

I'll get back to this in the future perhaps.

**Comment by evanwashere** [comment]
zig 0.8.0 is required or build from master branch `brew install zig --HEAD`

**Comment by fabiospampinato** [comment]
Now it works! Thank you!

But, the produced WASM is like 3x bigger than the one I got from emscripten.

Compiled with zig and `-O ReleaseSmall` I got [this](https://github.com/evanwashere/wasm/files/6604416/zstd.zig.wasm.zip) ~95kb wasm file.

Copiled with [emscripten](https://github.com/fabiospampinato/zstandard-wasm/blob/998de52d33b29efd7af882f58dacf4d981699e73/zstd/update.sh#L23) I got [this](https://github.com/evanwashere/wasm/files/6604417/zstd.emcc.wsm.zip) 37kb wasm file.

Happy to try other things if you have some other ideas on how to squeeze that down further.

**Comment by evanwashere** [comment]
you are missing exports elimination step and wasm-opt step which are done by emscripten

full script for your case would be
```bash
ldo="-O3 --export free --export malloc --export ZSTD_decompress --export ZSTD_findDecompressedSize"

zld="$(zig build-lib \
-lc \
-flto \
--strip \
-dynamic \
--name zstd \
--verbose-link \
-O ReleaseSmall \
-mcpu mvp-simd128 \
--single-threaded \
-target wasm32-wasi zstd.c \
2>&1 | sed "s/-O2//" | sed "s/--export-all/$ldo/")"

echo $zld
eval "$(brew --prefix llvm)/bin/$zld" && \
wasm-opt -Oz --dce --detect-features -o zstd.wasm zstd.wasm
```

after this the size difference is basically libc used by zig and emscripten

**Comment by fabiospampinato** [comment]
Jeez I totally forgot about that, I had commented those lines out initially and then forgot about them.

So I can get a 50kb wasm file with this:

```sh
cd zstd2

git clone https://github.com/facebook/zstd.git zstd
cd zstd
git checkout -b v1.5.0
cd ..

bash ./zstd/build/single_file_libs/combine.sh -r ./zstd/lib -o zstd.c ./zstd/build/single_file_libs/zstddeclib-in.c

ldo="-O3 --export free --export malloc --export ZSTD_decompress --export ZSTD_findDecompressedSize"

zld="$(~/Downloads/zig-macos-x86_64-0.8.0/zig build-lib \
-lc \
--strip \
-dynamic \
--name zstd \
--verbose-link \
-O ReleaseSmall \
-mcpu mvp-simd128 \
--single-threaded \
-target wasm32-wasi zstd.c \
2>&1 | sed "s/-O2//" | sed "s/--export-all/$ldo/")"

echo $zld

# eval "$(brew --prefix llvm) $zld"

wasm-snip zstd.wasm -k free -k malloc -k ZSTD_decompress -k ZSTD_findDecompressedSize -o zstd.wasm

./binaryen/bin/wasm-opt -Oz --dce --detect-features -o zstd.opt.wasm zstd.wasm
```

It weighs ~20kb more if I pass the `-flto` flags to zig, I've no idea what they do.

I'm skipping the llvm step since I don't have zig installed properly and that doesn't work for me, I think zig was complaining about my OS version or something.

How much does the wasm file that you are getting weigh? If it's significantly less than 37kb then I'll most probably go through the trouble of making this work properly eventually, if it isn't I think working with emscripten is just easier for me.

**Comment by evanwashere** [comment]
llvm step requires brew llvm to be installed
lto is link time optimization which might improve or worsen size while improving perf

without lto i get 48kb and with 46kb
at end emscripten is producing smaller bin and that's the best choice for you right now

note that size improvement mostly comes from replacing dlmalloc (9kb) and other things with slower and smaller versions but in your case that doesn't really matter
